### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by dsoronda** [atom/atom-dark-syntax#10]
[Enter steps to reproduce below:]

1. Created simple Console.cs application
2. Pressed Ctrl + Alt + o

**Atom Version**: 0.181.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [atom-dark-syntax](https://github.com/atom/atom-dark-syntax) package, v0.26.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /c:/Users/shoky/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni-sharp-server.coffee:117

TypeError: undefined is not a function
  at OmniSharpServerInstance.module.exports.OmniSharpServerInstance.getPortNumber (C:\Users\shoky\.atom\packages\omnisharp-atom\lib\omni-sharp-server\omni-sharp-server.coffee:106:25)
  at OmniSharpServerInstance.module.exports.OmniSharpServerInstance.start (C:\Users\shoky\.atom\packages\omnisharp-atom\lib\omni-sharp-server\omni-sharp-server.coffee:68:17)
  at OmniSharpServerInstance.module.exports.OmniSharpServerInstance.toggle (C:\Users\shoky\.atom\packages\omnisharp-atom\lib\omni-sharp-server\omni-sharp-server.coffee:114:50)
  at Object.module.exports.toggle (C:\Users\shoky\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.coffee:72:27)
  at atom-workspace.<anonymous> (C:\Users\shoky\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.coffee:14:61)
  at atom-workspace.handler (d:\ide\atom\app-0.181.0\resources\app\src\space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (d:\ide\atom\app-0.181.0\resources\app\node_modules\space-pen\vendor\jquery.js:4681:9)
  at atom-workspace.elemData.handle (d:\ide\atom\app-0.181.0\resources\app\node_modules\space-pen\vendor\jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (d:\ide\atom\app-0.181.0\resources\app\src\command-registry.js:243:29)
  at d:\ide\atom\app-0.181.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (d:\ide\atom\app-0.181.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (d:\ide\atom\app-0.181.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (d:\ide\atom\app-0.181.0\resources\app\src\window-event-handler.js:176:20)

```

### Commands

```
     -4:44.3 omnisharp-atom:toggle (atom-text-editor.editor)
     -4:38.8 atom-sharp:open:solution:browse (atom-text-editor.editor)
     -4:03.7 editor:newline (atom-text-editor.editor)
  4x -4:02.3 core:backspace (atom-text-editor.editor)
     -3:57.8 snippets:next-tab-stop (atom-text-editor.editor)
     -3:57.8 snippets:expand (atom-text-editor.editor)
  3x -3:50.9 editor:move-to-beginning-of-word (atom-text-editor.editor)
  2x -3:49.9 autocomplete:toggle (atom-text-editor.editor)
     -3:45.6 core:save (atom-text-editor.editor)
     -2:28.8 project-manager:toggle (div.settings-view.pane-item)
     -0:47.9 command-palette:toggle (atom-text-editor.editor)
     -0:40.9 omnisharp-atom:show-build (atom-text-editor.editor)
     -0:03.5 omnisharp-atom:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "seti-monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-sharp, v0.1.0
atom-typescript, v0.65.0
autocomplete-haxe, v0.2.0
autocomplete-plus, v2.1.6
autocomplete-plus-async, v0.22.0
language-csharp, v0.3.0
language-d, v2.0.0
language-haxe, v0.2.1
language-typescript, v0.15.0
linter, v0.11.1
omnisharp-atom, v0.1.6
project-manager, v1.15.5
seti-monokai, v0.3.1

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
This looks to be an issue with https://github.com/OmniSharp/omnisharp-atom, looks like Atom misreported which package caused it.

Looks like it has already been reported against that repository, https://github.com/OmniSharp/omnisharp-atom/issues/58
