### ISSUE TITLE
Uncaught Error: EBUSY, resource busy or locked 'H:\_REPO\deploy\scripts\patchMaker\post.http'

### ISSUE THREAD

**Issue by kisev** [atom/atom-dark-syntax#11]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Unknown Windows Version
**Thrown From**: [atom-dark-syntax](https://github.com/atom/atom-dark-syntax) package, v0.26.0
### Stack Trace

Uncaught Error: EBUSY, resource busy or locked 'H:_REPO\deploy\scripts\patchMaker\post.http'

```
At C:\Users\k_sevrjugin\AppData\Local\atom\app-0.187.0\resources\app\node_modules\q\q.js:128

Error: EBUSY, resource busy or locked 'H:\_REPO\deploy\scripts\patchMaker\post.http'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:362:29)
  at File.module.exports.File.readSync (C:\Users\k_sevrjugin\AppData\Local\atom\app-0.187.0\resources\app\node_modules\pathwatcher\lib\file.js:229:36)
  at TextBuffer.module.exports.TextBuffer.updateCachedDiskContentsSync (C:\Users\k_sevrjugin\AppData\Local\atom\app-0.187.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:991:85)
  at C:\Users\k_sevrjugin\AppData\Local\atom\app-0.187.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:1096:17
  at Emitter.module.exports.Emitter.emit (C:\Users\k_sevrjugin\AppData\Local\atom\app-0.187.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\k_sevrjugin\AppData\Local\atom\app-0.187.0\resources\app\node_modules\pathwatcher\lib\file.js:379:40
  at _fulfilled (C:\Users\k_sevrjugin\AppData\Local\atom\app-0.187.0\resources\app\node_modules\q\q.js:794:54)
  at self.promiseDispatch.done (C:\Users\k_sevrjugin\AppData\Local\atom\app-0.187.0\resources\app\node_modules\q\q.js:823:30)
  at Promise.promise.promiseDispatch (C:\Users\k_sevrjugin\AppData\Local\atom\app-0.187.0\resources\app\node_modules\q\q.js:756:13)
  at C:\Users\k_sevrjugin\AppData\Local\atom\app-0.187.0\resources\app\node_modules\q\q.js:564:44
  at flush (C:\Users\k_sevrjugin\AppData\Local\atom\app-0.187.0\resources\app\node_modules\q\q.js:110:17)
  at process._tickCallback (node.js:366:11)

```
### Commands

```
  5x -1:43.6 core:backspace (atom-text-editor.editor)
     -1:42.1 core:move-down (atom-text-editor.editor)
  5x -1:41.8 core:delete (atom-text-editor.editor)
     -1:39.8 core:move-down (atom-text-editor.editor)
  5x -1:39.8 core:delete (atom-text-editor.editor)
     -1:37.6 core:move-down (atom-text-editor.editor)
  5x -1:37.4 core:delete (atom-text-editor.editor)
     -1:35.4 core:save (atom-text-editor.editor)
     -1:26.2 core:copy (atom-text-editor.editor)
     -1:23.0 core:paste (atom-text-editor.editor)
  4x -1:10.6 core:backspace (atom-text-editor.editor)
     -0:57.4 core:save (atom-text-editor.editor)
     -0:31.5 core:backspace (atom-text-editor.editor)
  2x -0:30.8 core:delete (atom-text-editor.editor)
     -0:28.9 core:move-left (atom-text-editor.editor)
  2x -0:24.7 core:save (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by jlord** [comment]
Cross link to similar issue: https://github.com/atom/atom-dark-syntax/issues/11.

Seems like a Windows error and somewhere we need try and then try again before throwing.

**Comment by simurai** [comment]
Closing as `stale`.
