### ISSUE TITLE
Failed to activate the remember-session package

### ISSUE THREAD

**Issue by GuisenHuang** [atom/atom-dark-syntax#15]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.196.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-dark-syntax](https://github.com/atom/atom-dark-syntax) package, v0.26.0

### Stack Trace

Failed to activate the remember-session package

```
At Cannot read property 'x' of undefined

TypeError: Cannot read property 'x' of undefined
  at restoreDimensions (C:\Users\huang\.atom\packages\remember-session\lib\remember-session.coffee:70:4)
  at Object.module.exports.activate (C:\Users\huang\.atom\packages\remember-session\lib\remember-session.coffee:8:7)
  at Package.module.exports.Package.activateNow (E:\Atom\resources\app.asar\src\package.js:222:19)
  at E:\Atom\resources\app.asar\src\package.js:203:30
  at Package.module.exports.Package.measure (E:\Atom\resources\app.asar\src\package.js:147:15)
  at Package.module.exports.Package.activate (E:\Atom\resources\app.asar\src\package.js:195:14)
  at PackageManager.module.exports.PackageManager.activatePackage (E:\Atom\resources\app.asar\src\package-manager.js:434:21)
  at E:\Atom\resources\app.asar\node_modules\settings-view\lib\package-manager.js:316:29
  at exit (E:\Atom\resources\app.asar\node_modules\settings-view\lib\package-manager.js:41:16)
  at triggerExitCallback (E:\Atom\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (E:\Atom\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
  2x -2:31.5.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
minimap, v4.8.0
remember-session, v0.5.1

# Dev
No dev packages
```

**Comment by benogle** [comment]
You should uninstall remember-session, this behaviour is now the default.

**Comment by GuisenHuang** [comment]
Thanks.
