### ISSUE TITLE
Failed to activate the define-jump package

### ISSUE THREAD

**Issue by zur4ik** [atom/atom-dark-syntax#17]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1 Enterprise N
**Thrown From**: [atom-dark-syntax](https://github.com/atom/atom-dark-syntax) package, v0.27.0

### Stack Trace

Failed to activate the define-jump package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.activate (D:\Google Drive\Private\Configurations Files\Atom Editor\packages\define-jump\index.js:15:21)
    at Package.module.exports.Package.activateNow (C:\Users\Zura\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:240:19)
    at C:\Users\Zura\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:772:25
    at Emitter.module.exports.Emitter.emit (C:\Users\Zura\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Zura\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:222:20)
    at C:\Users\Zura\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\Zura\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\Zura\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (C:\Users\Zura\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Zura\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:241:29)
```

### Commands

```
  2x -2:22 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:21.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:21.1.0 settings-view:install-packages-and-themes (atom-text-editor.editor)
  2x -2:18.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:39.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:39.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:39.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:34.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:30.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:29.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:29.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:28.9.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:27 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:08.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:05.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.4.0 define-jump:to-original-definition (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ]
  }
}
```

### Installed Packages

```coffee
# User
browser-plus, v0.0.23
define-jump, v1.0.1
emmet, v2.3.10
highlight-selected, v0.10.1
minimap, v4.10.0
subword-navigation, v2.9.0

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
@izuzak @kevinsawicki This one is pretty weird - I'm not sure why this was thrown from atom-dark-syntax. What do you think?

**Comment by benogle** [comment]
In some cases it seems to pick the first one from the list. I was seeing this in the deprecation reporting data from windows too. I have not been able to reproduce it yet though.

**Comment by izuzak** [comment]
I added this to an issue in the Notifications package which tracks problems with picking the wrong package for the exception source: https://github.com/atom/notifications/issues/66

The problem related to the define-jump package has already been reported on that package's issue tracker (see https://github.com/hughsk/atom-define-jump/issues/2) so I'm going to close this.
