### ISSUE TITLE
Failed to activate the copy-config-info package

### ISSUE THREAD

**Issue by rugk** [atom/atom-dark-syntax#19]
[Enter steps to reproduce below:]

1. Copy config info.

**Atom Version**: 1.0.15
**System**: Windows 7
**Thrown From**: [atom-dark-syntax](https://github.com/atom/atom-dark-syntax) package, v0.27.0

### Stack Trace

Failed to activate the copy-config-info package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (D:\Users\%username%\.atom\packages\copy-config-info\lib\copy-config-info.coffee:3:21)
  at Package.module.exports.Package.activateNow (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:245:19)
  at C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\src\package.js:838:25
  at Emitter.module.exports.Emitter.emit (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:226:20)
  at C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:245:29)
  at C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\src\window-event-handler.js:184:20)

```

### Commands

```
     -6:15.5.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -5:54.4.0 window:toggle-dev-tools (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
     -5:49.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -5:47.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:47.5.0 markdown-table-formatter:format (atom-text-editor.editor)
     -5:46.4.0 core:save (atom-text-editor.editor.is-focused)
     -5:31.3.0 markdown-preview:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
     -1:26.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:25.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:11.4.0 command-palette:toggle (atom-text-editor.editor.mini.is-focused)
     -0:09.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:09.2.0 copy-config-info:copy (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "projectHome": "D:\\Users\\%username%\\GitHub",
    "disabledPackages": [
      "autocomplete-emojis"
    ]
  }
}
```

### Installed Packages

```coffee
# User
[...]

# Dev
No dev packages
```

**Comment by rugk** [comment]
Don't know why Atom said this should be created in this repo. (possibly I also copy & pasted it wrong)

So I'm closing this here.
