### ISSUE TITLE
Failed to activate the atom-autocomplete-php package

### ISSUE THREAD

**Issue by dschmidthawk** [atom/atom-dark-syntax#21]
[Enter steps to reproduce below:]

1. ...updated packages
2. ...

I'm a noob using atom and learning as I go. Apologies if this is obvious to the rest.

**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Pro
**Thrown From**: [atom-dark-syntax](https://github.com/atom/atom-dark-syntax) package, v0.27.0

### Stack Trace

Failed to activate the atom-autocomplete-php package

```
At Cannot read property 'indexOf' of undefined

TypeError: Cannot read property 'indexOf' of undefined
  at Object.module.exports.getMethodContext (C:\Users\Debbie S\.atom\packages\atom-autocomplete-php\lib\services\php-file-parser.coffee:577:25)
  at FunctionProvider.<anonymous> (C:\Users\Debbie S\.atom\packages\atom-autocomplete-php\lib\annotation\method-provider.coffee:57:33)
  at FunctionProvider.module.exports.FunctionProvider.registerAnnotations (C:\Users\Debbie S\.atom\packages\atom-autocomplete-php\lib\annotation\method-provider.coffee:140:12)
  at C:\Users\Debbie S\.atom\packages\atom-autocomplete-php\lib\annotation\abstract-provider.coffee:17:14
  at Workspace.module.exports.Workspace.observeTextEditors (R:\atom\atom\app-1.0.19\resources\app.asar\src\workspace.js:276:9)
  at FunctionProvider.module.exports.AbstractProvider.init (C:\Users\Debbie S\.atom\packages\atom-autocomplete-php\lib\annotation\abstract-provider.coffee:13:24)
  at AnnotationManager.module.exports.AnnotationManager.init (C:\Users\Debbie S\.atom\packages\atom-autocomplete-php\lib\annotation\annotation-manager.coffee:16:9)
  at Object.module.exports.activate (C:\Users\Debbie S\.atom\packages\atom-autocomplete-php\lib\peekmo-php-atom-autocomplete.coffee:64:28)
  at Package.module.exports.Package.activateNow (R:\atom\atom\app-1.0.19\resources\app.asar\src\package.js:245:19)
  at R:\atom\atom\app-1.0.19\resources\app.asar\src\package.js:226:30
  at Package.module.exports.Package.measure (R:\atom\atom\app-1.0.19\resources\app.asar\src\package.js:169:15)
  at Package.module.exports.Package.activate (R:\atom\atom\app-1.0.19\resources\app.asar\src\package.js:218:14)
  at PackageManager.module.exports.PackageManager.activatePackage (R:\atom\atom\app-1.0.19\resources\app.asar\src\package-manager.js:486:21)
  at R:\atom\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-manager.js:313:60
  at exit (R:\atom\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-manager.js:60:16)
  at triggerExitCallback (R:\atom\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (R:\atom\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

### Commands

```
     -8:33.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -8:00.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -7:45.5.0 settings-view:check-for-package-updates (atom-text-editor.editor)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.15.0
atom-bootstrap4, v1.2.13
atom-commander, v0.4.2
atom-html-preview, v0.1.11
atom-snippets, v0.1.1
Atom-Syntax-highlighting-for-Sass, v0.5.0
autoclose-html, v0.19.0
autocomplete-html-entities, v0.1.0
autocomplete-sass, v0.1.0
bootstrap-3-snippetset, v0.0.6
bootstrap4-snippets, v0.2.2
codeigniter, v0.2.0
codeigniter-nucleus, v0.4.3
color-picker, v2.0.13
compass, v0.9.1
copy-path, v0.1.1
css-snippets, v0.9.0
css-specificity, v0.2.2
giphy, v0.1.0
html-entities, v0.4.0
html-id-class-snippets, v1.4.1
icon-fonts, v1.7.1
linter, v1.8.1
linter-htmlhint, v0.1.1
linter-php, v1.0.5
linter-sass-lint, v0.4.1
php-analyser, v0.2.0
php-composer-completion, v0.3.4
pigments, v0.18.0
preview-plus, v1.2.6
Remote-FTP, v0.7.8
sass-autocompile, v0.10.7
sass-comment, v1.4.0
Sass-Syntax-Highlight, v0.1.1
sass-watch, v0.3.1
useful-context-menu, v0.3.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This seems to be [atom-autocomplete-php](https://atom.io/packages/atom-autocomplete-php)'s fault, not sure why it got reported here...can you please try disabling that package and see if it solves your issue?  If not, can you please move this issue over there?  Thanks :smile:.

**Comment by dschmidthawk** [comment]
Will do. When I clicked on the report issue button this is where it took me cuz it was thrown from the atom-dark-syntax package. I changed theme packages and am no longer getting the error...
