### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('...

### ISSUE THREAD

**Issue by weizai** [atom/atom-dark-syntax#26]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Unknown Windows Version
**Thrown From**: [atom-dark-syntax](https://github.com/atom/atom-dark-syntax) package, v0.27.0

### Stack Trace

Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN,NaN,NaN,1)') could not be parsed as a color.

```
At /C:/Users/coolv/.atom/packages/color-picker/lib/extensions/Alpha.coffee:93

Error: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN,NaN,NaN,1)') could not be parsed as a color.
    at Error (native)
    at Object._this.canvas.render (file:///C:/Users/coolv/.atom/packages/color-picker/lib/extensions/Alpha.coffee:103:35)
    at file:///C:/Users/coolv/.atom/packages/color-picker/lib/extensions/Alpha.coffee:112:29
    at Object.emit (file:///C:/Users/coolv/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
    at Object.emitColorChanged (file:///C:/Users/coolv/.atom/packages/color-picker/lib/extensions/Saturation.coffee:24:22)
    at file:///C:/Users/coolv/.atom/packages/color-picker/lib/extensions/Saturation.coffee:211:61
    at Object.emit (file:///C:/Users/coolv/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
    at Object.emitSelectionChanged (file:///C:/Users/coolv/.atom/packages/color-picker/lib/extensions/Saturation.coffee:18:22)
    at Object._this.control.setSelection (file:///C:/Users/coolv/.atom/packages/color-picker/lib/extensions/Saturation.coffee:200:43)
    at file:///C:/Users/coolv/.atom/packages/color-picker/lib/extensions/Saturation.coffee:208:30
    at Object.emit (file:///C:/Users/coolv/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
    at Object.emitInputColor (file:///C:/Users/coolv/.atom/packages/color-picker/lib/ColorPicker-view.coffee:234:22)
    at Object.open (file:///C:/Users/coolv/.atom/packages/color-picker/lib/ColorPicker-view.coffee:315:23)
    at atom-text-editor.<anonymous> (file:///C:/Users/coolv/.atom/packages/color-picker/lib/ColorPicker.coffee:42:68)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\coolv\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\coolv\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\coolv\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\coolv\AppData\Local\atom\app-1.3.2\resources\app.asar\src\atom-environment.js:1016:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (C:\Users\coolv\AppData\Local\atom\app-1.3.2\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\coolv\AppData\Local\atom\app-1.3.2\resources\atom.asar\renderer\api\lib\remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\coolv\AppData\Local\atom\app-1.3.2\resources\app.asar\src\context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (C:\Users\coolv\AppData\Local\atom\app-1.3.2\resources\app.asar\src\window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (C:\Users\coolv\AppData\Local\atom\app-1.3.2\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -3:16.9.0 pane:split-up (span.package-description)
  2x -2:19 color-picker:open (atom-text-editor.editor.is-focused)
     -1:45.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:45.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -1:44.2.0 core:save (atom-text-editor.editor.is-focused)
     -1:02.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:50.2.0 core:backspace (atom-text-editor.editor.is-focused)
  6x -0:49.4.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:43.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:35.8.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:21.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:20.8.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:10 core:backspace (atom-text-editor.editor.is-focused)
     -0:07.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.2.0 color-picker:open (atom-text-editor.editor.is-focused)
  3x -0:01.4.0 core:undo (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.14

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This looks like an issue with [color-picker](https://github.com/thomaslindstrom/color-picker), so I'm going to move this issue over there.  No idea why notifications didn't pick this up correctly.

**Comment by lee-dohm** [comment]
I'm going to re-add the uncaught-exception label. I'm going to be doing some investigation into improving the stack-trace heuristics next year some time and I want to track this :grinning:
