### ISSUE TITLE
Error with 'build'

### ISSUE THREAD

**Issue by Sogomn** [atom/atom-dark-syntax#27]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: SOGOMN-NOTEBOOK
**Thrown From**: [atom-dark-syntax](https://github.com/atom/atom-dark-syntax) package, v0.27.0

### Stack Trace

Uncaught TypeError: atom.project.getPaths(...).sort(...).find is not a function

```
At /C:/Users/Sogomn/.atom/packages/build/lib/build.js:200

TypeError: atom.project.getPaths(...).sort(...).find is not a function
  at Object.activePath (C:\Users\Sogomn\.atom\packages\build\lib\build.js:200:8)
  at Object.updateStatusBar (C:\Users\Sogomn\.atom\packages\build\lib\build.js:207:47)
  at C:\Users\Sogomn\.atom\packages\build\lib\build.js:131:20
  at Emitter.module.exports.Emitter.emit (C:\Users\Sogomn\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\Sogomn\AppData\Local\atom\app-1.0.19\resources\app.asar\src\pane-container.js:320:34
  at Emitter.module.exports.Emitter.emit (C:\Users\Sogomn\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (C:\Users\Sogomn\AppData\Local\atom\app-1.0.19\resources\app.asar\src\pane.js:250:22)
  at Pane.module.exports.Pane.activateItem (C:\Users\Sogomn\AppData\Local\atom\app-1.0.19\resources\app.asar\src\pane.js:314:21)
  at tabs-tab.<anonymous> (C:\Users\Sogomn\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:210:24)
  at space-pen-ul.jQuery.event.dispatch (C:\Users\Sogomn\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-ul.elemData.handle (C:\Users\Sogomn\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -4:18.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -4:17 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -4:15.4.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -4:14.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -4:13.5.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
     -4:13.1.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -4:12.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -4:12.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -3:49.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -3:45.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:45.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:45.4.0 settings-view:uninstall-packages (atom-text-editor.editor)
     -1:47.7.0 command-palette:toggle (atom-pane.pane.active)
     -1:43.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:43.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:43.4.0 settings-view:view-installed-themes (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "projectHome": "D:\\Entwicklung\\Atom",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
build, v0.54.1

# Dev
No dev packages
```

Appeared when I installed "Build".

**Comment by lee-dohm** [comment]
This appears to be an issue with the [build package](https://atom.io/packages/build). Would you mind reopening this there?
