### ISSUE TITLE
Failed to load the minimap package

### ISSUE THREAD

**Issue by only-online** [atom/atom-dark-syntax#29]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.189.0
**System**: Unknown Windows Version
**Thrown From**: [atom-dark-syntax](https://github.com/atom/atom-dark-syntax) package, v0.26.0

### Stack Trace

Failed to load the minimap package

```
At C:/Users/sanzh/.atom/packages/minimap/lib/main.js: Unexpected character '@' (28:0)
  26 |  * minimap and be available to the user through the minimap settings.
  27 |  */
> 28 | @include(PluginManagement)
     | ^
  29 | class Main {
  30 |   /**
  31 |    * Used only at export time.

SyntaxError: C:/Users/sanzh/.atom/packages/minimap/lib/main.js: Unexpected character '@' (28:0)
  26 |  * minimap and be available to the user through the minimap settings.
  27 |  */
> 28 | @include(PluginManagement)
     | ^
  29 | class Main {
  30 |   /**
  31 |    * Used only at export time.
  at raise (E:\Atom\resources\app\node_modules\babel-core\node_modules\acorn-babel\acorn_csp.js:343:15)
  at readToken (E:\Atom\resources\app\node_modules\babel-core\node_modules\acorn-babel\acorn_csp.js:1090:7)
  at next (E:\Atom\resources\app\node_modules\babel-core\node_modules\acorn-babel\acorn_csp.js:2117:5)
  at parseIdent (E:\Atom\resources\app\node_modules\babel-core\node_modules\acorn-babel\acorn_csp.js:3776:5)
  at parseBindingAtom (E:\Atom\resources\app\node_modules\babel-core\node_modules\acorn-babel\acorn_csp.js:2383:16)
  at parseVar (E:\Atom\resources\app\node_modules\babel-core\node_modules\acorn-babel\acorn_csp.js:2954:17)
  at parseVarStatement (E:\Atom\resources\app\node_modules\babel-core\node_modules\acorn-babel\acorn_csp.js:2842:5)
  at parseStatement (E:\Atom\resources\app\node_modules\babel-core\node_modules\acorn-babel\acorn_csp.js:2610:23)
  at parseTopLevel (E:\Atom\resources\app\node_modules\babel-core\node_modules\acorn-babel\acorn_csp.js:2567:18)
  at Object.exports.parse (E:\Atom\resources\app\node_modules\babel-core\node_modules\acorn-babel\acorn_csp.js:51:12)
  at module.exports (E:\Atom\resources\app\node_modules\babel-core\lib\babel\helpers\parse.js:18:21)
  at File.<anonymous> (E:\Atom\resources\app\node_modules\babel-core\lib\babel\transformation\file.js:397:12)
  at File.parse (E:\Atom\resources\app\node_modules\babel-core\lib\babel\transformation\file.js:379:21)
  at Object.transform (E:\Atom\resources\app\node_modules\babel-core\lib\babel\transformation\index.js:19:15)
  at transpile (E:\Atom\resources\app\src\babel.js:128:16)
  at Object.loadFile [as .js] (E:\Atom\resources\app\src\babel.js:165:67)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (E:\Atom\resources\app\src\package.js:678:34)
  at E:\Atom\resources\app\src\package.js:189:28
  at Package.module.exports.Package.measure (E:\Atom\resources\app\src\package.js:167:15)
  at Package.module.exports.Package.load (E:\Atom\resources\app\src\package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (E:\Atom\resources\app\src\package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (E:\Atom\resources\app\src\package-manager.js:460:30)
  at E:\Atom\resources\app\node_modules\settings-view\lib\package-manager.js:268:29
  at exit (E:\Atom\resources\app\node_modules\settings-view\lib\package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (E:\Atom\resources\app\src\buffered-process.js:63:47)
  at ChildProcess.<anonymous> (E:\Atom\resources\app\src\buffered-process.js:85:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -5:33.7 package-generator:generate-package (atom-text-editor.editor.mini.is-focused)
     -3:02.9 core:paste (atom-text-editor.editor.mini.is-focused)
     -3:01.9 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:36.9 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:36.5 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "atom-autocomplete-php",
      "color-picker",
      "autocomplete"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-css, v0.11.1
autocomplete-html-entities, v0.1.0
autocomplete-js-import, v1.0.1
autocomplete-json, v1.9.1
autocomplete-plus, v2.29.2
autocomplete-xml, v0.8.3
emmet, v2.4.3
minimap, v4.22.1
npm-autocomplete, v0.1.2
php-integrator-autocomplete-plus, v0.7.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please update Atom.  The latest version is currently 1.7.2.
